### ISSUE TITLE
package com.kscs.util.jaxb as runtime dependecy

### ISSUE THREAD

**Issue by cachescrubber** [mklemm/jaxb2-rich-contract-plugin#14]
Hi Mirko,

I just discovered that your plugin adds static code to the com.kscs.util.jaxb package within the generated-source folder. I see problems arising when multiple schemas are using your plugin. IMO the code schould be a runtime dependency or should be placed in the same package as the xjc generated code.

**Comment by mklemm** [comment]
Hi cachescrubber,
you can switch off the generation of this static code with the „-generate-tools=n“ option. Then you can add the jar (if repository configured like in your description!) to the runtime classpath of your code.
Please note that since version 1.5.0 the command-line options must be given AFTER the corresponding plugin activation option. Each of the plugin classes has its own „generate-tools“ option…

**Comment by cachescrubber** [comment]
Thanks Mirko,

generate-tools=n works as described. I should RTFM next time ;-)
