### ISSUE TITLE
fluent-builder: quote java keywords

### ISSUE THREAD

**Issue by CrystalMethod** [mklemm/jaxb2-rich-contract-plugin#22]
The fluent-builder plugin should generate builders with quoted java keywords:

```java
public Offers.Builder<_B> addPackage(final Iterable<? extends Package> package) {
```

vs.

```java
public Offers.Builder<_B> addPackage(final Iterable<? extends Package> _package) {
```

**Comment by mklemm** [comment]
Yes, you're right... It does so in many places, but not for parameters yet, unfortunately... But in any case, this most likely won't work with just plain JAXB (without the plugin) as well, since XJC will most likely try to generate an instance field named "package", which would also not compile.
You should use binding customizations to map the name of your property in XSD to a more java-friendly name.

**Comment by CrystalMethod** [comment]
Thx for the quick reply. Unfortunately it's not that easy because the is no field named ``package`` so custom binding is not applicable. Here is an extract of the XSD and the JAXB generated sources:

```xml
<xs:choice minOccurs="0" maxOccurs="unbounded">
  <xs:element ref="COM:Package">
    <xs:annotation>
      <xs:documentation>...</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element ref="COM:Route_List">
    <xs:annotation>
      <xs:documentation>...</xs:documentation>
    </xs:annotation>
  </xs:element>
  ...
</xs:choice>
```

```java
@XmlElements({
        @XmlElement(name = "Package", type = Package.class),
        @XmlElement(name = "Route_List", type = RouteList.class)
        ...
})
protected List<Object> ...;
```

**Comment by mklemm** [comment]
Ah, I see, so you are using the fact that the plugin can create concrete add... methods for a generic <choice>-collection.
In that case, I think you are right, the only way will be to make the plugin prefix all parameter names somehow, in order to avoid name collisions.

**Comment by CrystalMethod** [comment]
Ok, do you think you can fix this? I'm not that familiar with your plugin(s) to quickly provide a PR.

**Comment by mklemm** [comment]
Yes, this is only a small fix. To release a new version, however, it will take until tomorrow.

**Comment by CrystalMethod** [comment]
Great. Many thanks in advance.

**Comment by mklemm** [comment]
Hi, Release 1.9.0 is available from the central repository now.
Please check if it solves your issues.
There was another issue fixed: For your use case, if you were about to build a subclass of "Offers", the return type of the "addPackage"-Methods would have been wrong, so you couldn't "fluently" continue building your object. This has now been fixed in 1.9.0

**Comment by CrystalMethod** [comment]
Awesome, I will check version 1.9.0 today and comment here.

**Comment by CrystalMethod** [comment]
Builder source generation works, project compiles. I will close this issue for now and file a new if necessary.Thanks again.
