### ISSUE TITLE
Fluent Builder Command Line Options Do Not Work

### ISSUE THREAD

**Issue by tpunder** [mklemm/jaxb2-rich-contract-plugin#3]
-generate-tools -partial-clone and -narrow don't work when trying to use FluentBuilderPlugin.  It looks like the options are picked up by the DeepClonePlugin (which uses the same option names) instead of FluentBuilderPlugin even though I don't specify -Xclone.

As a hack to get it working I just renamed the option names in FluentBuilderPlugin and things work fine:  https://github.com/tpunder/jaxb2-rich-contract-plugin/commit/c95dcc9377a1d54b8b88c151e15b49c610f9c269

I'm not familiar with XJC plugins and how they handle command line arguments so I'm not sure if there is a better fix or not.

**Comment by mklemm** [comment]
Version 1.5.2 has been released on Maven central. Many generated names in source code can now be customized via command-line options. Please note: The groupId had to change to com.klemm-scs.util because of Sonatype Central hosting requirements.
This issue has now been resolved in a different way: Command line options must be given immediately after the corresponding plugin activation ("-X...") option. This way, option names do not to be globally unique, they are "namespaced" by the preceding activation option.
